# Generated by Django 3.1 on 2022-04-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verification'),
        ('users', '0002_auto_20220426_1501'),
    ]

    operations = [
    ]
